server:
  port: 7080
  forward-headers-strategy: framework
  #servlet:
  #  context-path: /resource-server
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/jdg.digital.p12
    key-store-password: yourpwd
    key-alias: jdg.digital
    certificate-private-key: file:/opt/vaadinfrontend/conf/private.key
    trust-certificate: file:/opt/vaadinfrontend/conf/certificate.pem

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://keycloak:8443/realms/project_admininstrator
            jwk-set-uri: https://keycloak:8443/realms/project_admininstrator/protocol/openid-connect/certs
            token-uri: https://keycloak:8443/realms/project_admininstrator/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: project_admininstrator_client
            client-secret: replaceme
            scope:
              - profile
              - email
              - openid
              - roles


logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE