server:
  port: 9080
  forward-headers-strategy: framework
  #servlet:
  #  context-path: /resource-server
  servlet:
    session:
      timeout: 1m

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://172.25.141.161:8443/realms/project_admininstrator
            jwk-set-uri: https://172.25.141.161:8443/realms/project_admininstrator/protocol/openid-connect/certs
        registration:
          keycloak:
            client-id: project_admininstrator_client
            client-secret: replaceme
            scope:
              - profile
              - email
              - openid
              - roles


logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

vaadin:
  # Reduce the heartbeat interval so that we get multiple ones before the session times out
  heartbeatInterval: 10
  # Don't let the heartbeat keep the sessions alive indefinitely
  closeIdleSessions: true